version: '3'
services:
  java-server:
    build: ./java
    volumes:
      - ./java/:/opt/app/
    ports:
      - "8080:8080"
  react-client:
    build: ./react-client
    volumes:
      - ./react-client/:/opt/app/
    ports:
      - "80:80"
      - "3000:3000"
